name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    # Setup tooling
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'

    # Setup RTCV
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/RTCV'
        ref: '506'
        path: 'RTCV'
    - name: Restore Nuget packages in RTCV
      run: nuget restore '.\RTCV\'
    - name: Build RTCV
      run: msbuild '.\RTCV\'

    # Build melonDS
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'melonDS-Vanguard'
    - name: Create build directory
      run: |
        New-Item -ItemType directory -Path ${{runner.workspace}}\melonDS-Vanguard\melonDS-Vanguard\out\build\x64-Debug
    - name: Configure
      run: |
        cd ${{runner.workspace}}\melonDS-Vanguard\melonDS-Vanguard\out\build\x64-Debug
        cmake ..\..\..\ -DENABLE_LTO=false -DDONT_COPY_FIRMWARE=true -DDONT_BUILD_EXTRA_SDL_CODE=true -DCI_BUILD_SHARED_LIBS=true -DCI_INCLUDE_EXTRA_LIBUI_LIBS=true
    - name: Build melonDS-Vanguard
      run: |
        cd ${{runner.workspace}}\melonDS-Vanguard\melonDS-Vanguard\out\build\x64-Debug
        msbuild melonDS.sln
